import {
  SHAREPOINT_TRANSIENT_HOST_QUERY_PARAM_NAMES,
} from './InlineAnchorRewriteHelper';
import {
  INLINE_NAVIGATION_ORIGINAL_HREF_ATTRIBUTE,
  INLINE_NAVIGATION_REWRITTEN_ATTRIBUTE,
} from './InlineNavigationAttributes';
import {
  DEFAULT_INLINE_DEEP_LINK_PARAM,
  MAX_DEEP_LINK_QUERY_VALUE_LENGTH,
} from './InlineDeepLinkHelper';

export function getInlineNavigationBridgeScript(
  baseUrlForRelativeLinks: string = '',
  allowedFileExtensions: string[] = [],
  allowedPathPrefixes: string[] = [],
  hostPageUrl: string = '',
  deepLinkQueryParamName: string = DEFAULT_INLINE_DEEP_LINK_PARAM,
  preservedHostQueryParamNames: string[] = [],
  enableHostDeepLinkUrls: boolean = true,
): string {
  const serializedBaseUrl = JSON.stringify(baseUrlForRelativeLinks || '');
  const serializedAllowedExtensions = JSON.stringify(
    (allowedFileExtensions.length > 0 ? allowedFileExtensions : ['.html', '.htm', '.aspx'])
      .map((extension) => extension.trim().toLowerCase())
      .filter((extension) => extension.length > 0)
      .map((extension) => (extension.startsWith('.') ? extension : `.${extension}`)),
  );
  const serializedAllowedPathPrefixes = JSON.stringify(
    allowedPathPrefixes.map((prefix) => prefix.trim()).filter((prefix) => prefix.length > 0),
  );
  const serializedHostPageUrl = JSON.stringify(hostPageUrl || '');
  const serializedDeepLinkQueryParamName = JSON.stringify(
    (deepLinkQueryParamName || '').trim() || DEFAULT_INLINE_DEEP_LINK_PARAM,
  );
  const serializedPreservedHostQueryParamNames = JSON.stringify(
    preservedHostQueryParamNames
      .map((paramName) => paramName.trim())
      .filter((paramName) => paramName.length > 0),
  );
  const serializedTransientHostQueryParamNames = JSON.stringify(
    SHAREPOINT_TRANSIENT_HOST_QUERY_PARAM_NAMES,
  );
  const serializedEnableHostDeepLinkUrls = JSON.stringify(enableHostDeepLinkUrls);
  return [
    '(function(){',
    '  try {',
    '    if (window.__uhvInlineNavBridgeInstalled) { return; }',
    '    window.__uhvInlineNavBridgeInstalled = true;',
    "    var interceptedEvents = ['pointerdown', 'mousedown', 'click'];",
    "    var blockedProtocols = ['javascript:', 'data:', 'mailto:', 'tel:'];",
    `    var configuredBaseUrl = ${serializedBaseUrl};`,
    `    var allowedFileExtensions = ${serializedAllowedExtensions};`,
    `    var configuredAllowedPathPrefixes = ${serializedAllowedPathPrefixes};`,
    `    var configuredHostPageUrl = ${serializedHostPageUrl};`,
    '    var currentHostPageUrl = configuredHostPageUrl;',
    `    var deepLinkQueryParamName = ${serializedDeepLinkQueryParamName};`,
    `    var preservedHostQueryParamNames = ${serializedPreservedHostQueryParamNames};`,
    `    var transientHostQueryParamNames = ${serializedTransientHostQueryParamNames};`,
    `    var enableHostDeepLinkUrls = ${serializedEnableHostDeepLinkUrls};`,
    `    var maxDeepLinkQueryValueLength = ${MAX_DEEP_LINK_QUERY_VALUE_LENGTH};`,
    '    var lastTargetUrl = "";',
    '    var lastTargetAt = 0;',
    '    var isSupportedNavigationEvent = function(event) {',
    '      if (!event) { return false; }',
    "      return typeof event.button !== 'number' || event.button >= 0 && event.button <= 2;",
    '    };',
    '    var getTargetElement = function(event) {',
    '      if (!event) { return null; }',
    '      var target = event.target;',
    '      if (!target) { return null; }',
    "      if (typeof Element !== 'undefined' && target instanceof Element) {",
    '        return target;',
    '      }',
    "      if (typeof Node !== 'undefined' && target instanceof Node) {",
    "        return target.parentElement || null;",
    '      }',
    '      return null;',
    '    };',
    '    var getComposedPathElements = function(event) {',
    "      if (!event || typeof event.composedPath !== 'function') { return []; }",
    '      var path;',
    '      try {',
    '        path = event.composedPath();',
    '      } catch (_error) {',
    '        return [];',
    '      }',
    '      if (!Array.isArray(path) || path.length === 0) { return []; }',
    '      var elements = [];',
    '      for (var index = 0; index < path.length; index += 1) {',
    '        var entry = path[index];',
    "        if (typeof Element !== 'undefined' && entry instanceof Element) {",
    '          elements.push(entry);',
    '          continue;',
    '        }',
    "        if (typeof Node !== 'undefined' && entry instanceof Node && entry.parentElement) {",
    '          elements.push(entry.parentElement);',
    '        }',
    '      }',
    '      return elements;',
    '    };',
    '    var findUniqueDescendantAnchor = function(element) {',
    "      if (!element || typeof element.querySelectorAll !== 'function') { return null; }",
    "      var anchors = element.querySelectorAll('a[href], a[xlink\\\\:href]');",
    '      if (!anchors || anchors.length !== 1) { return null; }',
    '      var anchor = anchors[0];',
    "      return anchor && String(anchor.tagName || '').toLowerCase() === 'a' ? anchor : null;",
    '    };',
    '    var hasExplicitHref = function(anchor) {',
    "      var hrefAttr = String((anchor && anchor.getAttribute && anchor.getAttribute('href')) || '').trim();",
    '      if (hrefAttr) { return true; }',
    '      try {',
    "        if (anchor && typeof anchor.getAttributeNS === 'function') {",
    "          return !!String(anchor.getAttributeNS('http://www.w3.org/1999/xlink', 'href') || '').trim();",
    '        }',
    '      } catch (_error) {',
    '        return false;',
    '      }',
    '      return false;',
    '    };',
    '    var resolveAnchor = function(event) {',
    '      var targetElement = getTargetElement(event);',
    '      if (!targetElement) { return null; }',
    "      if (typeof targetElement.closest === 'function') {",
    "        var closestAnchor = targetElement.closest('a');",
    "        if (closestAnchor && String(closestAnchor.tagName || '').toLowerCase() === 'a' && hasExplicitHref(closestAnchor)) {",
    '          return closestAnchor;',
    '        }',
    '      }',
    '      var uniqueDescendant = findUniqueDescendantAnchor(targetElement);',
    '      if (uniqueDescendant) {',
    '        return uniqueDescendant;',
    '      }',
    '      var pathElements = getComposedPathElements(event);',
    '      for (var pathIndex = 0; pathIndex < pathElements.length; pathIndex += 1) {',
    '        var pathElement = pathElements[pathIndex];',
    '        if (!pathElement) { continue; }',
    "        if (typeof pathElement.closest === 'function') {",
    "          var pathAnchor = pathElement.closest('a');",
    "          if (pathAnchor && String(pathAnchor.tagName || '').toLowerCase() === 'a' && hasExplicitHref(pathAnchor)) {",
    '            return pathAnchor;',
    '          }',
    '        }',
    '        var pathDescendant = findUniqueDescendantAnchor(pathElement);',
    '        if (pathDescendant) {',
    '          return pathDescendant;',
    '        }',
    '      }',
    "      var forcedContainer = typeof targetElement.closest === 'function'",
    "        ? targetElement.closest('.fc-event-forced-url')",
    '        : null;',
    '      if (forcedContainer) {',
    "        var forcedAnchor = forcedContainer.querySelector('a[href], a[xlink\\\\:href]');",
    "        if (forcedAnchor && String(forcedAnchor.tagName || '').toLowerCase() === 'a') {",
    '          return forcedAnchor;',
    '        }',
    '      }',
    '      return null;',
    '    };',
    '    var getAnchorHref = function(anchor) {',
    `      var wasRewritten = String((anchor && anchor.getAttribute && anchor.getAttribute('${INLINE_NAVIGATION_REWRITTEN_ATTRIBUTE}')) || '').trim() === '1';`,
    `      var inlineOriginalHref = String((anchor && anchor.getAttribute && anchor.getAttribute('${INLINE_NAVIGATION_ORIGINAL_HREF_ATTRIBUTE}')) || '').trim();`,
    '      if (wasRewritten && inlineOriginalHref) { return inlineOriginalHref; }',
    "      var hrefAttr = String((anchor && anchor.getAttribute && anchor.getAttribute('href')) || '').trim();",
    '      if (hrefAttr) { return hrefAttr; }',
    '      try {',
    "        if (anchor && typeof anchor.getAttributeNS === 'function') {",
    "          var namespacedHref = String(anchor.getAttributeNS('http://www.w3.org/1999/xlink', 'href') || '').trim();",
    '          if (namespacedHref) { return namespacedHref; }',
    '        }',
    '      } catch (_error) {',
    '        return "";',
    '      }',
    '      return "";',
    '    };',
    '    var isSamePageHashHref = function(href) {',
    "      return String(href || '').trim().indexOf('#') === 0;",
    '    };',
    '    var decodeHashFragment = function(fragment) {',
    '      try {',
    '        return decodeURIComponent(fragment);',
    '      } catch (_error) {',
    '        return fragment;',
    '      }',
    '    };',
    '    var findSamePageHashTarget = function(hashHref) {',
    "      if (hashHref === '#') { return null; }",
    '      var fragment = decodeHashFragment(hashHref.substring(1));',
    '      if (!fragment) { return null; }',
    '      return document.getElementById(fragment) || document.getElementsByName(fragment)[0] || null;',
    '    };',
    '    var navigateToSamePageHash = function(rawHref, event) {',
    "      var hashHref = String(rawHref || '').trim();",
    '      if (!isSamePageHashHref(hashHref)) { return false; }',
    '      var target = findSamePageHashTarget(hashHref);',
    '      if (!target) { return false; }',
    '      suppress(event);',
    '      try {',
    '        if (window.location) {',
    '          window.location.hash = hashHref;',
    '          return true;',
    '        }',
    '      } catch (_hashError) {',
    '      }',
    "      if (target && typeof target.scrollIntoView === 'function') {",
    '        target.scrollIntoView();',
    '        return true;',
    '      }',
    "      if (hashHref === '#' && typeof window.scrollTo === 'function') {",
    '        try {',
    '          window.scrollTo(0, 0);',
    '          return true;',
    '        } catch (_scrollError) {',
    '          return true;',
    '        }',
    '      }',
    '      return true;',
    '    };',
    '    var hasBlockedProtocol = function(href) {',
    "      var normalized = String(href || '').trim().toLowerCase();",
    "      for (var index = 0; index < blockedProtocols.length; index += 1) {",
    '        if (normalized.indexOf(blockedProtocols[index]) === 0) {',
    '          return true;',
    '        }',
    '      }',
    '      return false;',
    '    };',
    '    var normalizePath = function(value, ensureTrailingSlash) {',
    "      var normalized = String(value || '').trim().replace(/\\\\/g, '/');",
    "      try { normalized = decodeURIComponent(normalized); } catch (_error) { }",
    "      if (!normalized) { return ''; }",
    "      if (normalized.charAt(0) !== '/') { normalized = '/' + normalized; }",
    "      normalized = normalized.replace(/\\/{2,}/g, '/');",
    "      if (ensureTrailingSlash && normalized.charAt(normalized.length - 1) !== '/') { normalized += '/'; }",
    '      return normalized.toLowerCase();',
    '    };',
    '    var getEffectiveAllowedPathPrefixes = function(baseUrl) {',
    '      var result = [];',
    '      for (var index = 0; index < configuredAllowedPathPrefixes.length; index += 1) {',
    '        var normalizedPrefix = normalizePath(configuredAllowedPathPrefixes[index], true);',
    '        if (normalizedPrefix) { result.push(normalizedPrefix); }',
    '      }',
    '      if (result.length > 0) { return result; }',
    '      try {',
    '        var basePath = normalizePath(new URL(baseUrl).pathname, false);',
    "        var directoryEnd = basePath.lastIndexOf('/');",
    "        return directoryEnd >= 0 ? [basePath.substring(0, directoryEnd + 1)] : ['/'];",
    '      } catch (_error) {',
    '        return [];',
    '      }',
    '    };',
    '    var getAbsoluteConfiguredBaseUrl = function() {',
    "      var fallbackBase = String(document.baseURI || (window.location && window.location.href) || '').trim();",
    "      var configuredBase = String(configuredBaseUrl || '').trim();",
    '      try {',
    '        return new URL(configuredBase || fallbackBase, fallbackBase || undefined).toString();',
    '      } catch (_error) {',
    '        return fallbackBase;',
    '      }',
    '    };',
    '    var isEligibleTargetUrl = function(targetUrl) {',
    '      try {',
    '        var base = getAbsoluteConfiguredBaseUrl();',
    '        var target = new URL(targetUrl, base || undefined);',
    '        var parsedBase = new URL(base || target.toString());',
    "        if ((target.protocol !== 'https:' && target.protocol !== 'http:') || target.host.toLowerCase() !== parsedBase.host.toLowerCase()) { return false; }",
    '        var targetPath = normalizePath(target.pathname, false);',
    '        var hasAllowedExtension = false;',
    '        for (var extensionIndex = 0; extensionIndex < allowedFileExtensions.length; extensionIndex += 1) {',
    '          if (targetPath.endsWith(allowedFileExtensions[extensionIndex])) { hasAllowedExtension = true; break; }',
    '        }',
    '        if (!hasAllowedExtension) { return false; }',
    '        var allowedPrefixes = getEffectiveAllowedPathPrefixes(parsedBase.toString());',
    '        for (var prefixIndex = 0; prefixIndex < allowedPrefixes.length; prefixIndex += 1) {',
    '          var prefix = allowedPrefixes[prefixIndex];',
    "          if (targetPath === prefix.substring(0, prefix.length - 1) || targetPath.indexOf(prefix) === 0) { return true; }",
    '        }',
    '      } catch (_error) {',
    '        return false;',
    '      }',
    '      return false;',
    '    };',
    '    var shouldKeepNativeAnchorBehavior = function(anchor, event) {',
    "      if (!anchor || typeof anchor.getAttribute !== 'function') { return true; }",
    "      var target = String(anchor.getAttribute('target') || '').trim().toLowerCase();",
    "      var nonPrimaryButton = event && typeof event.button === 'number' && event.button !== 0;",
    '      var modifiedClick = !!(event && (event.metaKey || event.ctrlKey || event.shiftKey || event.altKey));',
    "      return !!target && target !== '_self' || nonPrimaryButton || modifiedClick;",
    '    };',
    '    var buildHostDeepLinkUrl = function(targetUrl) {',
    '      if (!enableHostDeepLinkUrls) { return ""; }',
    '      try {',
    "        var rawHostPageUrl = String(currentHostPageUrl || configuredHostPageUrl || '').trim();",
    '        if (!rawHostPageUrl) { return ""; }',
    "        var fallbackBase = String(document.baseURI || (window.location && window.location.href) || '').trim();",
    '        var hostPage = new URL(rawHostPageUrl, fallbackBase || undefined);',
    '        var target = new URL(targetUrl, getAbsoluteConfiguredBaseUrl() || undefined);',
    '        for (var transientIndex = 0; transientIndex < transientHostQueryParamNames.length; transientIndex += 1) {',
    '          var transientName = transientHostQueryParamNames[transientIndex];',
    '          var isExplicitlyPreserved = false;',
    '          for (var preservedIndex = 0; preservedIndex < preservedHostQueryParamNames.length; preservedIndex += 1) {',
    '            if (preservedHostQueryParamNames[preservedIndex].toLowerCase() === transientName) { isExplicitlyPreserved = true; break; }',
    '          }',
    '          if (!isExplicitlyPreserved) {',
    '            var currentParamNames = [];',
    '            hostPage.searchParams.forEach(function(_value, currentName) {',
    '              if (currentName.toLowerCase() === transientName) { currentParamNames.push(currentName); }',
    '            });',
    '            for (var currentIndex = 0; currentIndex < currentParamNames.length; currentIndex += 1) {',
    '              hostPage.searchParams.delete(currentParamNames[currentIndex]);',
    '            }',
    '          }',
    '        }',
    '        hostPage.hash = "";',
    '        var deepLinkValue = target.host.toLowerCase() === hostPage.host.toLowerCase()',
    '          ? target.pathname + target.search + target.hash',
    '          : target.toString();',
    '        if (!deepLinkValue || deepLinkValue.length > maxDeepLinkQueryValueLength) { return ""; }',
    '        hostPage.searchParams.set(deepLinkQueryParamName, deepLinkValue);',
    '        return hostPage.toString();',
    '      } catch (_error) {',
    '        return "";',
    '      }',
    '    };',
    '    var rewriteNativeTargetAnchor = function(anchor, targetUrl) {',
    '      var hostDeepLinkUrl = buildHostDeepLinkUrl(targetUrl);',
    '      if (!hostDeepLinkUrl || !anchor || typeof anchor.setAttribute !== "function") { return false; }',
    "      if (typeof anchor.removeAttribute === 'function') { anchor.removeAttribute('download'); }",
    `      anchor.setAttribute('${INLINE_NAVIGATION_ORIGINAL_HREF_ATTRIBUTE}', targetUrl);`,
    `      anchor.setAttribute('${INLINE_NAVIGATION_REWRITTEN_ATTRIBUTE}', '1');`,
    "      anchor.setAttribute('href', hostDeepLinkUrl);",
    '      return true;',
    '    };',
    '    var toAbsoluteUrl = function(rawHref) {',
    "      var base = String(document.baseURI || '').trim();",
    '      if (!base) {',
    "        base = String((window.location && window.location.href) || '').trim();",
    '      }',
    '      try {',
    '        return new URL(rawHref, base || undefined).toString();',
    '      } catch (_error) {',
    '        return String(rawHref || "").trim();',
    '      }',
    '    };',
    '    var suppress = function(event) {',
    "      if (!event || typeof event.preventDefault !== 'function') { return; }",
    '      event.preventDefault();',
    "      if (typeof event.stopPropagation === 'function') {",
    '        event.stopPropagation();',
    '      }',
    "      if (typeof event.stopImmediatePropagation === 'function') {",
    '        event.stopImmediatePropagation();',
    '      }',
    '      event.cancelBubble = true;',
    '      event.returnValue = false;',
    '    };',
    '    var emit = function(targetUrl, event) {',
    '      if (!targetUrl) { return; }',
    '      var now = Date.now();',
    '      if (lastTargetUrl === targetUrl && now - lastTargetAt < 500) {',
    '        suppress(event);',
    '        return;',
    '      }',
    '      lastTargetUrl = targetUrl;',
    '      lastTargetAt = now;',
    '      suppress(event);',
    '      try {',
    '        if (window.parent && window.parent !== window && typeof window.parent.postMessage === "function") {',
    "          window.parent.postMessage({ type: 'uhv-inline-nav', targetUrl: targetUrl }, '*');",
    '        }',
    '      } catch (_error) {',
    '        return;',
    '      }',
    '    };',
    '    var onInterceptedEvent = function(event) {',
    '      if (!isSupportedNavigationEvent(event)) { return; }',
    '      var anchor = resolveAnchor(event);',
    '      if (!anchor) { return; }',
    '      var rawHref = getAnchorHref(anchor);',
    '      if (!rawHref) { return; }',
    '      if (navigateToSamePageHash(rawHref, event)) { return; }',
    '      if (isSamePageHashHref(rawHref)) { return; }',
    '      if (hasBlockedProtocol(rawHref)) { return; }',
    '      var absoluteTargetUrl = toAbsoluteUrl(rawHref);',
    "      if (!absoluteTargetUrl || absoluteTargetUrl.charAt(0) === '#') { return; }",
    '      if (!isEligibleTargetUrl(absoluteTargetUrl)) { return; }',
    '      if (shouldKeepNativeAnchorBehavior(anchor, event)) {',
    '        rewriteNativeTargetAnchor(anchor, absoluteTargetUrl);',
    '        return;',
    '      }',
    '      emit(absoluteTargetUrl, event);',
    '    };',
    '    var onNestedNavigationMessage = function(event) {',
    "      if (!event || !event.source || typeof document.querySelectorAll !== 'function') { return; }",
    "      var nestedFrames = document.querySelectorAll('iframe[data-uhv-inline-src], iframe[data-uhv-nested-src]');",
    '      var isKnownNestedFrame = false;',
    '      for (var frameIndex = 0; frameIndex < nestedFrames.length; frameIndex += 1) {',
    '        try {',
    '          if (nestedFrames[frameIndex].contentWindow === event.source) { isKnownNestedFrame = true; break; }',
    '        } catch (_error) {',
    '          continue;',
    '        }',
    '      }',
    '      if (!isKnownNestedFrame) { return; }',
    "      var payload = event && event.data;",
    "      if (!payload || payload.type !== 'uhv-inline-nav' || typeof payload.targetUrl !== 'string') { return; }",
    '      var targetUrl = payload.targetUrl.trim();',
    '      if (!targetUrl || !isEligibleTargetUrl(targetUrl)) { return; }',
    '      try {',
    '        if (window.parent && window.parent !== window && typeof window.parent.postMessage === "function") {',
    "          window.parent.postMessage({ type: 'uhv-inline-nav', targetUrl: targetUrl }, '*');",
    '        }',
    '      } catch (_error) {',
    '        return;',
    '      }',
    '    };',
    '    var onHostPageUrlMessage = function(event) {',
    '      if (!event || event.source !== window.parent) { return; }',
    '      var payload = event.data;',
    "      if (!payload || payload.type !== 'uhv-inline-host-page-url' || typeof payload.hostPageUrl !== 'string') { return; }",
    '      try {',
    '        var candidateHostPage = new URL(payload.hostPageUrl);',
    "        if (candidateHostPage.protocol !== 'https:' && candidateHostPage.protocol !== 'http:') { return; }",
    "        var configuredHostPage = String(configuredHostPageUrl || '').trim();",
    '        if (configuredHostPage) {',
    '          var configuredHost = new URL(configuredHostPage, candidateHostPage.toString());',
    '          if (configuredHost.host.toLowerCase() !== candidateHostPage.host.toLowerCase()) { return; }',
    '        }',
    '        currentHostPageUrl = candidateHostPage.toString();',
    '      } catch (_error) {',
    '        return;',
    '      }',
    '    };',
    '    for (var eventIndex = 0; eventIndex < interceptedEvents.length; eventIndex += 1) {',
    '      var eventName = interceptedEvents[eventIndex];',
    '      document.addEventListener(eventName, onInterceptedEvent, true);',
    '    }',
    "    window.addEventListener('message', onNestedNavigationMessage);",
    "    window.addEventListener('message', onHostPageUrlMessage);",
    '    try {',
    '      if (window.parent && window.parent !== window && typeof window.parent.postMessage === "function") {',
    "        window.parent.postMessage({ type: 'uhv-inline-ready' }, '*');",
    '      }',
    '    } catch (_error) {',
    '      return;',
    '    }',
    '  } catch (_error) {',
    '    return;',
    '  }',
    '})();',
  ].join('\n');
}
